
#include "typedef.h"
#include "graphic.h"

uint8 icon_heart[256] = 
{
NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,NONE_COL,NONE_COL,RED,RED,NONE_COL,NONE_COL,NONE_COL,NONE_COL,RED,RED,NONE_COL,NONE_COL,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,NONE_COL,RED,RED,RED,RED,NONE_COL,NONE_COL,RED,RED,RED,RED,NONE_COL,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,NONE_COL,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,NONE_COL,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,NONE_COL,NONE_COL,RED,RED,RED,RED,RED,RED,RED,RED,NONE_COL,NONE_COL,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,RED,RED,RED,RED,RED,RED,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,RED,RED,RED,RED,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,RED,RED,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,
NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL,NONE_COL
};

uint8 icon_close[256] = 
{
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,GREY,BLACK,
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,GREY,BLACK,
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,GREY,BLACK,
WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,WHITE,WHITE,GREY,BLACK,
WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,WHITE,WHITE,BLACK,BLACK,WHITE,WHITE,WHITE,GREY,BLACK,
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,GREY,BLACK,
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,GREY,BLACK,
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,GREY,BLACK,
WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,WHITE,WHITE,BLACK,BLACK,WHITE,WHITE,WHITE,GREY,BLACK,
WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,WHITE,WHITE,GREY,BLACK,
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,GREY,BLACK,
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,GREY,BLACK,
WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,GREY,BLACK,
WHITE,GREY,GREY,GREY,GREY,GREY,GREY,GREY,GREY,GREY,GREY,GREY,GREY,GREY,GREY,BLACK,
BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK
};

